// Code generated by build-locales.mjs from Language::ALL. DO NOT EDIT.
package ms

import (
	_ "embed"
	blasphem "github.com/sospedra/blasphem/packages/go/v2"
)

//go:embed locale.pack
var pack []byte

//go:embed locale.detect
var detect []byte

// Locale contains the embedded ms model, lexicon, and detection slice.
var Locale = blasphem.Locale{Code: "ms", Pack: pack, PackSHA256: "fdd5f51352d65ab531a8b305e17a3b31a966d73b769c9dbdca07abf2f784307d", Detect: detect, DetectSHA256: "54072266fdc60c880754cef3529c1e77c8ccfa4618c1510fe5c6ae405aab8325"}
