// Code generated by `blasphem-train locales-table --format go` from `Language::ALL`. DO NOT EDIT.

package blasphem

// locales lists every supported code in registry order with its aliases.
var locales = []struct {
	code    string
	aliases []string
}{
	{code: "en", aliases: []string{}},
	{code: "zh", aliases: []string{}},
	{code: "es", aliases: []string{}},
	{code: "ar", aliases: []string{}},
	{code: "ms", aliases: []string{"id"}},
	{code: "pt", aliases: []string{}},
	{code: "fr", aliases: []string{}},
	{code: "hi", aliases: []string{}},
	{code: "ru", aliases: []string{}},
	{code: "ja", aliases: []string{}},
	{code: "de", aliases: []string{}},
	{code: "tr", aliases: []string{}},
	{code: "vi", aliases: []string{}},
	{code: "ko", aliases: []string{}},
	{code: "it", aliases: []string{}},
}
