import { execFileSync } from "node:child_process";
import { cpSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const coreSource = resolve(packageRoot, "../javascript-common/src");
const coreCopy = resolve(packageRoot, "src/core");
const distribution = resolve(packageRoot, "dist");
for (const name of ["BlasphemFileIO.swift", "BlasphemDownloadStore.swift"]) {
  cpSync(resolve(packageRoot, "../apple/Sources/Blasphem", name), resolve(packageRoot, "ios", name));
}
for (const name of ["BlasphemRemoteStore.kt"]) {
  const source = readFileSync(resolve(packageRoot, "../android/engine/src/main/kotlin/me/sospedra/blasphem", name), "utf8");
  const generated = source.replace("package me.sospedra.blasphem", "package com.margelo.nitro.blasphem");
  writeFileSync(resolve(packageRoot, "android/src/main/java/com/margelo/nitro/blasphem", name), generated);
}
const { version } = JSON.parse(readFileSync(resolve(packageRoot, "package.json"), "utf8"));
const manifest = readFileSync(resolve(packageRoot, "../../resources/packs/manifest.json"));
const manifestIntegrity = { bytes: manifest.length, sha256: createHash("sha256").update(manifest).digest("hex") };
writeFileSync(resolve(packageRoot, "src/version.generated.ts"), `// Generated by scripts/build.mjs.\nexport const VERSION = ${JSON.stringify(version)};\nexport const MANIFEST_INTEGRITY = ${JSON.stringify(manifestIntegrity)};\n`);
const kotlinRelease = `// Generated by scripts/build.mjs. Do not edit.\npackage com.margelo.nitro.blasphem\n\ninternal const val RELEASE_VERSION = ${JSON.stringify(version)}\ninternal const val MANIFEST_BYTES = ${manifestIntegrity.bytes}L\ninternal const val MANIFEST_SHA256 = ${JSON.stringify(manifestIntegrity.sha256)}\n`;
writeFileSync(resolve(packageRoot, "android/src/main/java/com/margelo/nitro/blasphem/Release.generated.kt"), kotlinRelease);

rmSync(distribution, { recursive: true, force: true });
rmSync(coreCopy, { recursive: true, force: true });
cpSync(coreSource, coreCopy, { recursive: true });
const coreFiles = readdirSync(coreCopy).filter((name) => name.endsWith(".ts")).length;
if (coreFiles === 0) throw new Error(`${coreSource} has no TypeScript sources`);

execFileSync("pnpm", ["exec", "tsc", "--project", resolve(packageRoot, "tsconfig.json")], { stdio: "inherit", cwd: packageRoot });
console.log(`status=built core_files=${coreFiles} entries=${readdirSync(distribution).filter((name) => name.endsWith(".js")).join(",")}`);
