// Code generated by build-locales.mjs from Language::ALL. DO NOT EDIT.
package tr

import (
	_ "embed"
	blasphem "github.com/sospedra/blasphem/packages/go/v2"
)

//go:embed locale.pack
var pack []byte

//go:embed locale.detect
var detect []byte

// Locale contains the embedded tr model, lexicon, and detection slice.
var Locale = blasphem.Locale{Code: "tr", Pack: pack, PackSHA256: "a811dc8570921f17345a3736fdf6a0635f2467e26516bfdf0d66b84dd54f07d9", Detect: detect, DetectSHA256: "a87b2b5b84af0391212670dd2344a64fa9a77480566ada92cba2e0762d5e9b96"}
