// Code generated by build-locales.mjs from Language::ALL. DO NOT EDIT.
package vi

import (
	_ "embed"
	blasphem "github.com/sospedra/blasphem/packages/go"
)

//go:embed locale.pack
var pack []byte

//go:embed locale.detect
var detect []byte

// Locale contains the embedded vi model, lexicon, and detection slice.
var Locale = blasphem.Locale{Code: "vi", Pack: pack, PackSHA256: "1a3b4e608be7bfa37437207819f2841088c2a6450f33cd87f501452ee2c2e4da", Detect: detect, DetectSHA256: "01a49dc3bd36c2461c4787895c83b6d20e84066115f907178821d13c20ed519e"}
