// Code generated by build-locales.mjs from Language::ALL. DO NOT EDIT.
package ko

import (
	_ "embed"
	blasphem "github.com/sospedra/blasphem/packages/go"
)

//go:embed locale.pack
var pack []byte

//go:embed locale.detect
var detect []byte

// Locale contains the embedded ko model, lexicon, and detection slice.
var Locale = blasphem.Locale{Code: "ko", Pack: pack, PackSHA256: "be20f98447d269f20fb440ae5f48cc228e7e8462e8190e896e9260508d775d8e", Detect: detect, DetectSHA256: "c670cc52736dffacfaed04e908cc7e3ae8f549456faf4d1c0ec03ecf5be6ef16"}
