[package]
name = "blasphem-napi"
version.workspace = true
edition = "2024"
rust-version = "1.85"
publish = false
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
blasphem = { path = "../..", default-features = false, features = ["language-detection"] }
napi = { version = "3", default-features = false, features = ["napi8"] }
napi-derive = "3"

[build-dependencies]
napi-build = "2"

[lints]
workspace = true
