// Code generated by build-locales.mjs from Language::ALL. DO NOT EDIT.
package ar

import (
	_ "embed"
	blasphem "github.com/sospedra/blasphem/packages/go/v2"
)

//go:embed locale.pack
var pack []byte

//go:embed locale.detect
var detect []byte

// Locale contains the embedded ar model, lexicon, and detection slice.
var Locale = blasphem.Locale{Code: "ar", Pack: pack, PackSHA256: "b54e8e9e84dffa173df93510f5206b42cb2416707f612cc866253b3ce4cfa179", Detect: detect, DetectSHA256: "44fcb92ba36692ed5077b7c6a5dc6c1b273c4a2fd62dc3fb96dcf6eff6faba64"}
