// Code generated by build-locales.mjs from Language::ALL. DO NOT EDIT.
package id

import "github.com/sospedra/blasphem/packages/go/locales/ms"

// Locale is the id storage alias for the ms locale.
var Locale = ms.Locale
