// Code generated by build-locales.mjs from Language::ALL. DO NOT EDIT.
package zh

import (
	_ "embed"
	blasphem "github.com/sospedra/blasphem/packages/go"
)

//go:embed locale.pack
var pack []byte

//go:embed locale.detect
var detect []byte

// Locale contains the embedded zh model, lexicon, and detection slice.
var Locale = blasphem.Locale{Code: "zh", Pack: pack, PackSHA256: "2b9d262edc8e6cc0ce19dca9bc937c7c7ca99e7c16227d6eecf56f21c4480473", Detect: detect, DetectSHA256: "8ba36ecb073ad70b6a8a6f73f868f6c287813b92b1803c13dce5c017ca073d63"}
