// Generated by `blasphem-train locales-table` from `Language::ALL`. Do not edit.
export const LOCALES = [
  { code: "en", aliases: [] },
  { code: "zh", aliases: [] },
  { code: "es", aliases: [] },
  { code: "ar", aliases: [] },
  { code: "ms", aliases: ["id"] },
  { code: "pt", aliases: [] },
  { code: "fr", aliases: [] },
  { code: "hi", aliases: [] },
  { code: "ru", aliases: [] },
  { code: "ja", aliases: [] },
  { code: "de", aliases: [] },
  { code: "tr", aliases: [] },
  { code: "vi", aliases: [] },
  { code: "ko", aliases: [] },
  { code: "it", aliases: [] },
] as const;
export type LocaleCode = (typeof LOCALES)[number]["code"];
