// Code generated by build-locales.mjs from Language::ALL. DO NOT EDIT.
package es

import (
	_ "embed"
	blasphem "github.com/sospedra/blasphem/packages/go"
)

//go:embed locale.pack
var pack []byte

//go:embed locale.detect
var detect []byte

// Locale contains the embedded es model, lexicon, and detection slice.
var Locale = blasphem.Locale{Code: "es", Pack: pack, PackSHA256: "cde7a8b85d58490b394f8c1f65e55e37ceab195cc42bc1ff91f46b904ca3cc53", Detect: detect, DetectSHA256: "ec223cf0cb1b8ded3d38328793561270f1574b94b79446d31da9229f84fe6823"}
