// Generated by `blasphem-train locales-table --format kotlin` from `Language::ALL`. Do not edit.

package me.sospedra.blasphem.gradle

internal val LOCALES: List<Pair<String, List<String>>> = listOf(
    "en" to listOf(),
    "zh" to listOf(),
    "es" to listOf(),
    "ar" to listOf(),
    "ms" to listOf("id"),
    "pt" to listOf(),
    "fr" to listOf(),
    "hi" to listOf(),
    "ru" to listOf(),
    "ja" to listOf(),
    "de" to listOf(),
    "tr" to listOf(),
    "vi" to listOf(),
    "ko" to listOf(),
    "it" to listOf(),
)
