// Generated by scripts/sync-packs.mjs. Do not edit.
package me.sospedra.blasphem.gradle

internal const val RELEASE_VERSION = "1.0.0"
internal const val MANIFEST_BYTES = 3968L
internal const val MANIFEST_SHA256 = "e1a6378847715c4ec4ed670441b812e7f3f9dec884db47f1e1b7b2b32a96f266"
