[package]
name = "blasphem-bench"
version.workspace = true
edition = "2024"
rust-version = "1.85"
publish = false
license = "Apache-2.0"

[dependencies]
anyhow.workspace = true
clap.workspace = true
blasphem-language = { path = "../blasphem-language" }
serde.workspace = true
serde_jcs.workspace = true
serde_json = { workspace = true, features = ["float_roundtrip"] }
sha2.workspace = true
thiserror.workspace = true
blasphem = { path = "../blasphem" }

[target.'cfg(target_os = "macos")'.dependencies]
libc = "=0.2.189"

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
