import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");
const check = process.argv.includes("--check");
if (process.argv.slice(2).some((arg) => arg !== "--check")) {
  throw new Error("Usage: node packages/go/scripts/build-locales.mjs [--check]");
}
const registry = execFileSync("cargo", ["run", "--quiet", "-p", "blasphem-train", "--", "locales-table", "--format", "go", "--output", "/dev/stdout"], { cwd: root, encoding: "utf8" });
const locales = [...registry.matchAll(/code: "([a-z]+)", aliases: \[\]string\{([^}]*)\}/g)].map((match) => ({
  code: match[1], aliases: [...match[2].matchAll(/"([a-z]+)"/g)].map((alias) => alias[1]),
}));
const codes = locales.map(({ code }) => code);
if (codes.length === 0) throw new Error("The Rust registry returned no locales");
function output(path, bytes) {
  path = resolve(root, "packages/go/locales", path);
  if (check) {
    if (!readFileSync(path).equals(Buffer.from(bytes))) throw new Error("Stale locale file: " + path);
  } else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, bytes);
  }
}
function go(path, source) {
  output(path, execFileSync("gofmt", [], { input: source }));
}
const module = "github.com/sospedra/blasphem/packages/go";
for (const code of codes) {
  const pack = readFileSync(resolve(root, "resources/packs", code + ".pack"));
  const detect = readFileSync(resolve(root, "resources/packs", code + ".detect"));
  const hash = (bytes) => createHash("sha256").update(bytes).digest("hex");
  output(code + "/locale.pack", pack);
  output(code + "/locale.detect", detect);
  go(code + "/locale.go", `// Code generated by build-locales.mjs from Language::ALL. DO NOT EDIT.
package ${code}
import (
  _ "embed"
  blasphem "${module}"
)
//go:embed locale.pack
var pack []byte
//go:embed locale.detect
var detect []byte
// Locale contains the embedded ${code} model, lexicon, and detection slice.
var Locale = blasphem.Locale{Code: "${code}", Pack: pack, PackSHA256: "${hash(pack)}", Detect: detect, DetectSHA256: "${hash(detect)}"}
`);
}
go("all/locales.go", `// Code generated by build-locales.mjs from Language::ALL. DO NOT EDIT.
package all
import (
  blasphem "${module}"
  ${codes.map((code) => '"' + module + '/locales/' + code + '"').join("\n")}
)
// Locales contains every release locale in registry order.
var Locales = []blasphem.Locale{${codes.map((code) => code + ".Locale").join(", ")}}
`);
for (const { code, aliases } of locales) {
  for (const alias of aliases) {
    go(`${alias}/locale.go`, `// Code generated by build-locales.mjs from Language::ALL. DO NOT EDIT.
package ${alias}
import "${module}/locales/${code}"
// Locale is the ${alias} storage alias for the ${code} locale.
var Locale = ${code}.Locale
`);
  }
}
console.log(`status=${check ? "verified" : "generated"} locales=${codes.length}`);
