// Code generated by build-locales.mjs from Language::ALL. DO NOT EDIT.
package de

import (
	_ "embed"
	blasphem "github.com/sospedra/blasphem/packages/go/v2"
)

//go:embed locale.pack
var pack []byte

//go:embed locale.detect
var detect []byte

// Locale contains the embedded de model, lexicon, and detection slice.
var Locale = blasphem.Locale{Code: "de", Pack: pack, PackSHA256: "ab5a5fd10367af250975c8c89608e456fc5de5b15d56cafda8648c63663967eb", Detect: detect, DetectSHA256: "863dabd8a2ce16af1bccc60a45aae7b86c8c96368a7ffc0838525574bdbb9bd3"}
