import { copyFileSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, extname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { canonicalPacks, copyPack, loadPacks, replaceDirectory } from "../../../scripts/packs.mjs";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const projectRoot = resolve(packageRoot, "../..");
const source = resolve(process.argv[2] ?? canonicalPacks);
const notice = resolve(projectRoot, "NOTICE");
const packs = resolve(packageRoot, "packs");
const manifest = '<manifest xmlns:android="http://schemas.android.com/apk/res/android" />\n';
const files = loadPacks(source).files;
const staged = mkdtempSync(resolve(packageRoot, ".packs-export-"));
const kotlinRoot = resolve(packageRoot, "engine/src/main/kotlin/me/sospedra/blasphem");
const pluginRoot = resolve(packageRoot, "gradle-plugin/src/main/kotlin/me/sospedra/blasphem/gradle");
const version = readFileSync(resolve(packageRoot, "gradle.properties"), "utf8").match(/^VERSION_NAME=(.+)$/m)[1];
const manifestBytes = readFileSync(resolve(source, "manifest.json"));
const release = `// Generated by scripts/sync-packs.mjs. Do not edit.\npackage me.sospedra.blasphem\n\ninternal const val RELEASE_VERSION = "${version}"\ninternal const val MANIFEST_BYTES = ${manifestBytes.length}L\ninternal const val MANIFEST_SHA256 = "${createHash("sha256").update(manifestBytes).digest("hex")}"\n`;
mkdirSync(pluginRoot, { recursive: true });
writeFileSync(resolve(kotlinRoot, "Release.generated.kt"), release);
writeFileSync(resolve(pluginRoot, "Release.generated.kt"), release.replace("package me.sospedra.blasphem", "package me.sospedra.blasphem.gradle"));
writeFileSync(resolve(pluginRoot, "Locales.generated.kt"), readFileSync(resolve(kotlinRoot, "Locales.generated.kt"), "utf8").replace("package me.sospedra.blasphem", "package me.sospedra.blasphem.gradle"));

function writeModule(file) {
  const kind = extname(file.name).slice(1);
  const code = file.name.slice(0, -kind.length - 1);
  const main = resolve(staged, code, kind, "src/main");
  mkdirSync(resolve(main, "resources/META-INF"), { recursive: true });
  copyPack(file, resolve(main, "assets/blasphem", file.name));
  copyFileSync(notice, resolve(main, "resources/META-INF/NOTICE"));
  writeFileSync(resolve(main, "AndroidManifest.xml"), manifest);
  writeFileSync(resolve(staged, code, kind, "build.gradle.kts"), "// Configured by the root build. Required by Android lint inputs.\n");
}

try {
  for (const file of files) writeModule(file);
  replaceDirectory(staged, packs);
} finally {
  rmSync(staged, { recursive: true, force: true });
}
const bytes = files.reduce((sum, file) => sum + file.bytes.length, 0);
console.log(`status=synced modules=${files.length} total_mb=${(bytes / 1048576).toFixed(2)} source=${source}`);
