// Code generated by build-locales.mjs from Language::ALL. DO NOT EDIT.
package ru

import (
	_ "embed"
	blasphem "github.com/sospedra/blasphem/packages/go"
)

//go:embed locale.pack
var pack []byte

//go:embed locale.detect
var detect []byte

// Locale contains the embedded ru model, lexicon, and detection slice.
var Locale = blasphem.Locale{Code: "ru", Pack: pack, PackSHA256: "32495e970a8a3e2fc924672952ac50f9e84d41a7191042367e27df76a7e1c0dc", Detect: detect, DetectSHA256: "08d9d833de6639df644afe51ed45f2848fefb13ea302f9f0f08056f3d94dd493"}
