// Code generated by build-locales.mjs from Language::ALL. DO NOT EDIT.
package hi

import (
	_ "embed"
	blasphem "github.com/sospedra/blasphem/packages/go/v2"
)

//go:embed locale.pack
var pack []byte

//go:embed locale.detect
var detect []byte

// Locale contains the embedded hi model, lexicon, and detection slice.
var Locale = blasphem.Locale{Code: "hi", Pack: pack, PackSHA256: "ef9d230f61327739eb4fb2e7f626a4527e489d14a7ee8c804e4c042abece612d", Detect: detect, DetectSHA256: "3d91d62dddbaee82569d96b50d93ff3c1c757cf760b5ded64bbb921db062cbcf"}
