// Code generated by build-locales.mjs from Language::ALL. DO NOT EDIT.
package en

import (
	_ "embed"
	blasphem "github.com/sospedra/blasphem/packages/go/v2"
)

//go:embed locale.pack
var pack []byte

//go:embed locale.detect
var detect []byte

// Locale contains the embedded en model, lexicon, and detection slice.
var Locale = blasphem.Locale{Code: "en", Pack: pack, PackSHA256: "b64f3bf43d986f1dbe862c5e488e28d2d7f1f0ca6d01ad5d30285553b505c55f", Detect: detect, DetectSHA256: "d039692b2ce374e1f5fa12c423468c4d665b86323f498d41dae2537c4fc49035"}
