// Code generated by build-locales.mjs from Language::ALL. DO NOT EDIT.
package all

import (
	blasphem "github.com/sospedra/blasphem/packages/go/v2"
	"github.com/sospedra/blasphem/packages/go/v2/locales/ar"
	"github.com/sospedra/blasphem/packages/go/v2/locales/de"
	"github.com/sospedra/blasphem/packages/go/v2/locales/en"
	"github.com/sospedra/blasphem/packages/go/v2/locales/es"
	"github.com/sospedra/blasphem/packages/go/v2/locales/fr"
	"github.com/sospedra/blasphem/packages/go/v2/locales/hi"
	"github.com/sospedra/blasphem/packages/go/v2/locales/it"
	"github.com/sospedra/blasphem/packages/go/v2/locales/ja"
	"github.com/sospedra/blasphem/packages/go/v2/locales/ko"
	"github.com/sospedra/blasphem/packages/go/v2/locales/ms"
	"github.com/sospedra/blasphem/packages/go/v2/locales/pt"
	"github.com/sospedra/blasphem/packages/go/v2/locales/ru"
	"github.com/sospedra/blasphem/packages/go/v2/locales/tr"
	"github.com/sospedra/blasphem/packages/go/v2/locales/vi"
	"github.com/sospedra/blasphem/packages/go/v2/locales/zh"
)

// Locales contains every release locale in registry order.
var Locales = []blasphem.Locale{en.Locale, zh.Locale, es.Locale, ar.Locale, ms.Locale, pt.Locale, fr.Locale, hi.Locale, ru.Locale, ja.Locale, de.Locale, tr.Locale, vi.Locale, ko.Locale, it.Locale}
