// Code generated by build-locales.mjs from Language::ALL. DO NOT EDIT.
package ja

import (
	_ "embed"
	blasphem "github.com/sospedra/blasphem/packages/go"
)

//go:embed locale.pack
var pack []byte

//go:embed locale.detect
var detect []byte

// Locale contains the embedded ja model, lexicon, and detection slice.
var Locale = blasphem.Locale{Code: "ja", Pack: pack, PackSHA256: "10109292eebb0af28b129124cbf0ffa94c57aacda00991747f5d2b0d2049dc06", Detect: detect, DetectSHA256: "8159e39a3afe9f8237150d4bcae48bed390c1fb75f0e5dc07837d4617844f579"}
