// Code generated by build-locales.mjs from Language::ALL. DO NOT EDIT.
package pt

import (
	_ "embed"
	blasphem "github.com/sospedra/blasphem/packages/go/v2"
)

//go:embed locale.pack
var pack []byte

//go:embed locale.detect
var detect []byte

// Locale contains the embedded pt model, lexicon, and detection slice.
var Locale = blasphem.Locale{Code: "pt", Pack: pack, PackSHA256: "d70ed55988ef1bca1bc0e606f9bf3262f82a0849757382a4c43288ae9851d800", Detect: detect, DetectSHA256: "6bd5d85418b2cdf365930e0a3b6f827fada3dae52ce88ec39fa6825bc9fcc364"}
