// Code generated by build-locales.mjs from Language::ALL. DO NOT EDIT.
package fr

import (
	_ "embed"
	blasphem "github.com/sospedra/blasphem/packages/go"
)

//go:embed locale.pack
var pack []byte

//go:embed locale.detect
var detect []byte

// Locale contains the embedded fr model, lexicon, and detection slice.
var Locale = blasphem.Locale{Code: "fr", Pack: pack, PackSHA256: "f57e70fde203b1d05d0b41731e27c588e8dfa99d7378a2589d8e05022ddb9a2a", Detect: detect, DetectSHA256: "190872f6dfd0741c17069569be211067ea3d7e43249481ca6257c0bd974feaaf"}
