//! Generates the TypeScript locale table from `Language::ALL`, so JavaScript
//! never hand-copies the language list or the `id` alias.

use std::fs;
use std::io;
use std::path::Path;

use blasphem::Language;

/// The languages a generated table can be written in.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TableFormat {
    TypeScript,
    Go,
    Python,
    Swift,
    Kotlin,
}

impl TableFormat {
    /// Parses a `--format` value.
    #[must_use]
    pub fn parse(value: &str) -> Option<Self> {
        match value {
            "ts" | "typescript" => Some(Self::TypeScript),
            "go" => Some(Self::Go),
            "py" | "python" => Some(Self::Python),
            "swift" => Some(Self::Swift),
            "kt" | "kotlin" => Some(Self::Kotlin),
            _ => None,
        }
    }
}

fn entries() -> Vec<(String, Vec<String>)> {
    Language::ALL
        .into_iter()
        .map(|language| {
            let code = language.code().to_ascii_lowercase();
            let aliases = (language.storage_code() != language.code())
                .then(|| language.storage_code().to_ascii_lowercase())
                .into_iter()
                .collect();
            (code, aliases)
        })
        .collect()
}

/// The generated source for one format, byte for byte.
#[must_use]
pub fn locales_source(format: TableFormat) -> String {
    match format {
        TableFormat::TypeScript => locales_table(),
        TableFormat::Go => go_table(),
        TableFormat::Python => python_table(),
        TableFormat::Swift => swift_table(),
        TableFormat::Kotlin => kotlin_table(),
    }
}

fn quoted(values: &[String]) -> String {
    values
        .iter()
        .map(|value| format!("\"{value}\""))
        .collect::<Vec<_>>()
        .join(", ")
}

fn go_table() -> String {
    let mut source = String::from(
        "// Code generated by `blasphem-train locales-table --format go` from `Language::ALL`. DO NOT EDIT.\n\n\
         package blasphem\n\n\
         // locales lists every supported code in registry order with its aliases.\n\
         var locales = []struct {\n\tcode    string\n\taliases []string\n}{\n",
    );
    for (code, aliases) in entries() {
        source.push_str(&format!(
            "\t{{code: \"{code}\", aliases: []string{{{}}}}},\n",
            quoted(&aliases)
        ));
    }
    source.push_str("}\n");
    source
}

fn python_table() -> String {
    let mut source = String::from(
        "# Generated by `blasphem-train locales-table --format python` from `Language::ALL`. Do not edit.\n\n\
         LOCALES: tuple[tuple[str, tuple[str, ...]], ...] = (\n",
    );
    for (code, aliases) in entries() {
        let alias_tuple = if aliases.is_empty() {
            "()".to_owned()
        } else {
            format!("({},)", quoted(&aliases))
        };
        source.push_str(&format!("    (\"{code}\", {alias_tuple}),\n"));
    }
    source.push_str(")\n");
    source
}

fn swift_table() -> String {
    let mut source = String::from(
        "// Generated by `blasphem-train locales-table --format swift` from `Language::ALL`. Do not edit.\n\n\
         let locales: [(code: String, aliases: [String])] = [\n",
    );
    for (code, aliases) in entries() {
        source.push_str(&format!(
            "    (code: \"{code}\", aliases: [{}]),\n",
            quoted(&aliases)
        ));
    }
    source.push_str("]\n");
    source
}

fn kotlin_table() -> String {
    let mut source = String::from(
        "// Generated by `blasphem-train locales-table --format kotlin` from `Language::ALL`. Do not edit.\n\n\
         package me.sospedra.blasphem\n\n\
         internal val LOCALES: List<Pair<String, List<String>>> = listOf(\n",
    );
    for (code, aliases) in entries() {
        source.push_str(&format!(
            "    \"{code}\" to listOf({}),\n",
            quoted(&aliases)
        ));
    }
    source.push_str(")\n");
    source
}

/// The generated TypeScript source, byte for byte.
#[must_use]
pub fn locales_table() -> String {
    let mut source = String::from(
        "// Generated by `blasphem-train locales-table` from `Language::ALL`. Do not edit.\n\
         export const LOCALES = [\n",
    );
    for language in Language::ALL {
        let code = language.code().to_ascii_lowercase();
        let aliases: Vec<String> = (language.storage_code() != language.code())
            .then(|| format!("\"{}\"", language.storage_code().to_ascii_lowercase()))
            .into_iter()
            .collect();
        source.push_str(&format!(
            "  {{ code: \"{code}\", aliases: [{}] }},\n",
            aliases.join(", ")
        ));
    }
    source.push_str(
        "] as const;\n\
         export type LocaleCode = (typeof LOCALES)[number][\"code\"];\n",
    );
    source
}

/// Writes the table to `output` in `format`, creating parent directories.
///
/// # Errors
///
/// Returns the I/O error of the directory or file write.
pub fn write_locales_table(output: &Path, format: TableFormat) -> io::Result<()> {
    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(output, locales_source(format))
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use super::locales_table;

    #[test]
    fn the_table_lists_fifteen_locales_with_the_id_alias_on_ms() {
        let table = locales_table();

        assert_eq!(table.matches("{ code:").count(), 15);
        assert!(table.contains("{ code: \"ms\", aliases: [\"id\"] },"));
        assert!(table.contains("{ code: \"en\", aliases: [] },"));
        assert!(table.ends_with("export type LocaleCode = (typeof LOCALES)[number][\"code\"];\n"));
    }

    #[test]
    fn every_format_lists_fifteen_locales_with_the_id_alias_on_ms() {
        use super::{TableFormat, locales_source};

        let go = locales_source(TableFormat::Go);
        assert_eq!(go.matches("{code:").count(), 15);
        assert!(go.contains("{code: \"ms\", aliases: []string{\"id\"}},"));
        let python = locales_source(TableFormat::Python);
        assert_eq!(python.matches("    (\"").count(), 15);
        assert!(python.contains("(\"ms\", (\"id\",)),"));
        let swift = locales_source(TableFormat::Swift);
        assert_eq!(swift.matches("    (code:").count(), 15);
        assert!(swift.contains("    (code: \"ms\", aliases: [\"id\"]),"));
        assert!(swift.contains("    (code: \"en\", aliases: []),"));
        let kotlin = locales_source(TableFormat::Kotlin);
        assert_eq!(kotlin.matches(" to listOf(").count(), 15);
        assert!(kotlin.contains("    \"ms\" to listOf(\"id\"),"));
        assert!(kotlin.contains("    \"en\" to listOf(),"));
        assert!(kotlin.starts_with("// Generated by"));
        assert!(kotlin.contains("\npackage me.sospedra.blasphem\n"));
        assert_eq!(TableFormat::parse("go"), Some(TableFormat::Go));
        assert_eq!(TableFormat::parse("swift"), Some(TableFormat::Swift));
        assert_eq!(TableFormat::parse("kt"), Some(TableFormat::Kotlin));
        assert_eq!(TableFormat::parse("rust"), None);
    }

    #[test]
    fn the_committed_tables_are_current() {
        use super::{TableFormat, locales_source};

        let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
        for (relative, format) in [
            ("packages/go/locales.go", TableFormat::Go),
            (
                "packages/python/python/blasphem/_locales.py",
                TableFormat::Python,
            ),
            (
                "packages/apple/Sources/Blasphem/Locales.generated.swift",
                TableFormat::Swift,
            ),
            (
                "packages/android/engine/src/main/kotlin/me/sospedra/blasphem/Locales.generated.kt",
                TableFormat::Kotlin,
            ),
        ] {
            let path = root.join(relative);
            let contents = std::fs::read_to_string(&path)
                .unwrap_or_else(|error| panic!("{}: {error}", path.display()));
            assert_eq!(contents, locales_source(format), "regenerate {relative}");
        }
    }

    #[test]
    fn the_committed_table_is_current() {
        let committed = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../packages/javascript-common/src/locales.generated.ts");
        let contents = std::fs::read_to_string(&committed)
            .unwrap_or_else(|error| panic!("{}: {error}", committed.display()));

        assert_eq!(
            contents,
            locales_table(),
            "run: cargo run -p blasphem-train -- locales-table --output packages/javascript-common/src/locales.generated.ts"
        );
    }
}
