//! Generates the TypeScript locale table from `Language::ALL`, so JavaScript
//! never hand-copies the language list or the `id` alias.

use std::fs;
use std::io;
use std::path::Path;

use blasphem::Language;

/// The generated TypeScript source, byte for byte.
#[must_use]
pub fn locales_table() -> String {
    let mut source = String::from(
        "// Generated by `blasphem-train locales-table` from `Language::ALL`. Do not edit.\n\
         export const LOCALES = [\n",
    );
    for language in Language::ALL {
        let code = language.code().to_ascii_lowercase();
        let aliases: Vec<String> = (language.storage_code() != language.code())
            .then(|| format!("\"{}\"", language.storage_code().to_ascii_lowercase()))
            .into_iter()
            .collect();
        source.push_str(&format!(
            "  {{ code: \"{code}\", aliases: [{}] }},\n",
            aliases.join(", ")
        ));
    }
    source.push_str(
        "] as const;\n\
         export type LocaleCode = (typeof LOCALES)[number][\"code\"];\n",
    );
    source
}

/// Writes the table to `output`, creating parent directories.
///
/// # Errors
///
/// Returns the I/O error of the directory or file write.
pub fn write_locales_table(output: &Path) -> io::Result<()> {
    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(output, locales_table())
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use super::locales_table;

    #[test]
    fn the_table_lists_fifteen_locales_with_the_id_alias_on_ms() {
        let table = locales_table();

        assert_eq!(table.matches("{ code:").count(), 15);
        assert!(table.contains("{ code: \"ms\", aliases: [\"id\"] },"));
        assert!(table.contains("{ code: \"en\", aliases: [] },"));
        assert!(table.ends_with("export type LocaleCode = (typeof LOCALES)[number][\"code\"];\n"));
    }

    #[test]
    fn the_committed_table_is_current() {
        let committed = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../packages/core/src/locales.generated.ts");
        let contents = std::fs::read_to_string(&committed)
            .unwrap_or_else(|error| panic!("{}: {error}", committed.display()));

        assert_eq!(
            contents,
            locales_table(),
            "run: cargo run -p blasphem-train -- locales-table --output packages/core/src/locales.generated.ts"
        );
    }
}
