// Code generated by build-locales.mjs from Language::ALL. DO NOT EDIT.
package it

import (
	_ "embed"
	blasphem "github.com/sospedra/blasphem/packages/go/v2"
)

//go:embed locale.pack
var pack []byte

//go:embed locale.detect
var detect []byte

// Locale contains the embedded it model, lexicon, and detection slice.
var Locale = blasphem.Locale{Code: "it", Pack: pack, PackSHA256: "5fa04d4be73595072eb276622821503e52302b61a7bbdd282b1b1047f89c434f", Detect: detect, DetectSHA256: "92924c25f9c8b35b65fc51e3a90ba9e8fe473f30bc77d19e63ed756cf88e7240"}
