# Generated by `blasphem-train locales-table --format python` from `Language::ALL`. Do not edit.

LOCALES: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("en", ()),
    ("zh", ()),
    ("es", ()),
    ("ar", ()),
    ("ms", ("id",)),
    ("pt", ()),
    ("fr", ()),
    ("hi", ()),
    ("ru", ()),
    ("ja", ()),
    ("de", ()),
    ("tr", ()),
    ("vi", ()),
    ("ko", ()),
    ("it", ()),
)
